### ISSUE TITLE
Error during install with command line packages on Windows

### ISSUE THREAD

**Issue by kireerik** [boltpkg/bolt#207]
| Title               | Description
| --------------------|------------
| Version             | 0.22.4
| Type                | Issue
| node                | 11.3.0
| Operating System    | Windows 10

I am recieving the following error on `bolt install`:
```bash
[4/4] Linking workspace binaries...
error Error: Can't read shim path from 'project/packages/project/index.js', it doesn't appear to be a cmd-shim
error     at cb (AppData/Local/Yarn/Data/global/node_modules/bolt/dist/modern/utils/fs.js:154:75)
error     at AnyPromise (AppData/Local/Yarn/Data/global/node_modules/typeable-promisify/index.js:13:3)
error     at new Promise (<anonymous>)
error     at promisify (AppData/Local/Yarn/Data/global/node_modules/typeable-promisify/index.js:12:40)
error     at readCmdShim (AppData/Local/Yarn/Data/global/node_modules/bolt/dist/modern/utils/fs.js:154:42)
error     at cmdShim (AppData/Local/Yarn/Data/global/node_modules/bolt/dist/modern/utils/fs.js:96:88)
error     at createWindowsSymlink (AppData/Local/Yarn/Data/global/node_modules/bolt/dist/modern/utils/fs.js:122:18)
error     at Object.symlink (AppData/Local/Yarn/Data/global/node_modules/bolt/dist/modern/utils/fs.js:134:18)
```

**Comment by ajaymathur** [comment]
Hey @kireerik , can also push a minimal reproducible example repository? It will be easier for me to debug and understand the issue. 🙂

**Comment by kireerik** [comment]
Hi @ajaymathur, I think you can reproduce this issue in this repository: https://github.com/kireerik/refo

You will get the error for this package first (https://github.com/kireerik/refo/tree/master/index/index/core/index) and if you remove these lines from it's package.json, you will no longer get the error for that package:
https://github.com/kireerik/refo/blob/5f5757cc1110e55abc851116e8b55cbc6ccfbe78/index/index/core/index/package.json#L4-L6

After this, you will get the error for this package (https://github.com/kireerik/refo/tree/master/index/index/index). This package it self is very minimal. Also if you remove these lines here (https://github.com/kireerik/refo/blob/5f5757cc1110e55abc851116e8b55cbc6ccfbe78/index/index/index/package.json#L4-L6) then you will no longer get the error as well.

Note: This issue is related to command-line packages (https://blog.npmjs.org/post/118810260230/building-a-simple-command-line-tool-with-npm).

**Comment by ajaymathur** [comment]
@kireerik Thanks for sharing the repository. It is taking time since I do not have access to any windows machine at home at the moment. All my friends are travelling due to holiday. I should get a windows machine next week, I will take sometime and look into the issue then. Thanks 🙂
